name: picker_instagram
description: "A Flutter package for picking images or the videos or both from the Gallery."
version: 0.0.6
homepage:
repository: https://github.com/jatinkumar1999/picker_instagram.git

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  video_thumbnail: ^0.5.3
  camera: ^0.11.0+1
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_image_compress: ^2.3.0
  provider: ^6.1.2
  permission_handler: ^11.3.1
  cropperx: ^1.1.1
  custom_image_view: ^5.0.2
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  photo_gallery: ^2.2.1
  transparent_image: ^2.0.1
  video_player: ^2.9.1
  video_compress: ^3.1.2
  google_fonts: ^6.2.1
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
